# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name=meals.models.upload_directory_path)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', related_query_name='meal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratting', to='meals.Meal')),
                ('memeber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
