# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratting',
            old_name='memeber',
            new_name='member',
        ),
    ]
