# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='following',
        ),
        migrations.AddField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='followers', related_query_name='followers', to='members.Member'),
        ),
    ]
