# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20161013_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(blank=True, default='', related_name='followers', related_query_name='followers', to='members.Member'),
        ),
    ]
